<?php

/**
 * @file
 * Register hooks for ShortCodes that use Twig templates.
 */

/**
 * Implements hook_theme().
 */
function ucb_migration_shortcodes_theme() {
  return [
     // Box.
    'shortcode_box' => [
      'variables' => ['title' => NULL, 'color' => NULL, 'style' => NULL, 'float' => NULL, 'text' => ''],
    ],
    // Icon.
    'shortcode_icon' => [
      'variables' => ['shape' => NULL, 'color' => NULL, 'size' => NULL, 'wrapper' => NULL, 'text' => ''],
    ],
    // Button.
    'shortcode_button' => [
      'variables' => ['link' => NULL, 'ico' => NULL, 'title' => NULL, 'color' => NULL, 'size' => NULL, 'style' => NULL, 'text' => '',],
    ],
    // Column.
    'shortcode_column' => [
      'variables' => ['size' => NULL, 'order' => NULL, 'text' => ''],
    ],
    // Expand.
    'shortcode_expand' => [
      'variables' => ['title' => NULL, 'style' => NULL, 'text' => ''],
    ],
    // Countup.
    'shortcode_countup' => [
      'variables' => ['text' => ''],
    ],
    // Callout.
    'shortcode_callout' => [
      'variables' => ['size' => NULL, 'text' => ''],
    ],
    // Give.
    'shortcode_give' => [
      'variables' => ['link' => NULL, 'ico' => NULL, 'title' => NULL, 'color' => NULL, 'size' => NULL, 'style' => NULL, 'text' => '',],
    ],
    // Map.
    'shortcode_map' => [
      'variables' => ['size' => NULL, 'maplocation' => NULL, 'mapfragment' => NULL, 'text' => ''],
    ],
    // ImageCaption.
    'shortcode_imagecaption' => [
      'variables' => ['align' => NULL, 'text' => ''],
    ],
    // ButtonGroup.
    'shortcode_buttongroup' => [
      'variables' => ['color' => NULL, 'size' => NULL, 'text' => '',],
    ],
    // Invisible.
    'shortcode_invisible' => [
      'variables' => ['text' => ''],
    ],
    // Google Calendar.
    'shortcode_googlecalendar' => [
      'variables' => ['text' => ''],
    ],
    // Print.
    'shortcode_print' => [
      'variables' => ['text' => ''],
    ],
    // Clear.
    'shortcode_clear' => [
      'variables' => ['text' => ''],
    ],
    // Close Margin.
    'shortcode_closemargin' => [
      'variables' => ['text' => ''],
    ],
    // Responsive Table.
    'shortcode_responsivetable' => [
      'variables' => ['breakpoint' => NULL, 'text' => ''],
    ],
    // Column List.
    'shortcode_columnlist' => [
      'variables' => ['columns' => NULL, 'text' => ''],
    ],
    // List Item.
    'shortcode_listitem' => [
      'variables' => ['text' => ''],
    ],
    // Countdown.
    'shortcode_countdown' => [
      'variables' => ['style' => NULL, 'size' => NULL, 'background' => NULL, 'text' => ''],
    ],
    // Blockquote.
    'shortcode_blockquote' => [
      'variables' => ['style' => NULL, 'float' => NULL, 'icon' => NULL, 'text' => ''],
    ],
    // Masonry Images.
    'shortcode_masonryimages' => [
      'variables' => ['columns' => NULL, 'text' => ''],
    ],
  ];
}
